# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Setup Java 21
      - uses: actions/setup-java@v4
      - with:
          java-version: '21'
          distribution: 'temurin'

      - name: Fix line endings for Windows-Linux
      - run: sed -i 's/\r$//' ./gradlew

      - name: Fix gradlew
      - run: chmod +x ./gradlew

      - name: Gradle Assemble
      - uses: ./gradlew assemble
