name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Fix line endings for Windows-Linux
      run: sed -i 's/\r$//' ./gradlew

    - name: Gradlew executable
      run: chmod +x ./gradlew
  assemble:

    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Fix line endings for Windows-Linux
      run: sed -i 's/\r$//' ./gradlew

    - name: Gradlew executable
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew assemble

    - name: Get project version
      id: get_version
      run: echo "::set-output name=VERSION::$(./gradlew -q printVersion)"

    - name: Grab artifact
      uses: actions/upload-artifact@v4
      with:
        name: CrazyEnchantments Imperium Fork v${{ steps.get_version.outputs.VERSION }}
        path: jars/*.jar

  publish:

    runs-on: ubuntu-latest
    needs: assemble
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Download target artifact
      uses: actions/download-artifact@v4
      with:
        name: CrazyEnchantments Imperium Fork v${{ needs.assemble.outputs.VERSION }}
        path: ./downloaded-artifacts

    - name: Setup Release
      id: new_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: alpha - build ${{ github.run_number }}
        name: Build ${{ github.run_number }}
        body: Automatic build upload. This is build ${{ github.run_number }}
        draft: false
        prerelease: false
        files: ./downloaded-artifacts/*.jar
